apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-production
  labels:
    type: wordpress-pv-production
spec:
  storageClassName: aws-efs
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /
    server: fs-a63a15e7.efs.ap-southeast-1.amazonaws.com
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pvc
  namespace: production
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      type: "wordpress-pv-production"