apiVersion: v1
kind: Service
metadata:
  name: wordpress-production
  namespace: production
  labels:
    app: wordpress
spec:
  ports:
    - port: 8500
      targetPort: 80
  selector:
    app: wordpress
  type: NodePort
