apiVersion: v1
kind: Service
metadata:
  name: landing-page-stagging
  namespace: stagging
  labels:
    app: landing-page
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: landing-page
  type: NodePort

