apiVersion: v1
kind: Service
metadata:
  name: pesbuk-stagging
  namespace: stagging
  labels:
      app: pesbuk
spec:
  ports:
    - port: 8300
      targetPort: 80
  selector:
    app: pesbuk
  type: NodePort

