---

- hosts: client
  become: yes
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install pip
    apt: name=python-pip state=present update_cache=true
  - name: install python setup tools
    apt: name=python-setuptools state=present update_cache=true
  - name: Install docker-pip
    pip:
      name: docker,docker-py
  - name: login to DockerHub remote registry using your account
    docker_login:
      username: ikhsannugs
      password: Akundocker123
      email: ikhsanfajar17@gmail.com
